const products = [
  {
    id: "rose-chapter",
    category: "bookmark",
    name: "Rose Chapter",
    priceCAD: 6.5,
    image: "assets/bookmark-rose.png",
    descriptions: {
      en: "A soft pink bookmark with a romantic floral touch.",
      fr: "Un marque-page rose doux avec une touche florale romantique.",
    },
  },
  {
    id: "sage-notes",
    category: "bookmark",
    name: "Sage Notes",
    priceCAD: 6.5,
    image: "assets/bookmark-sage.png",
    descriptions: {
      en: "A calm, clean style with sage green and warm accents.",
      fr: "Un style calme et clean avec vert sauge et accents lumineux.",
    },
  },
  {
    id: "moon-margin",
    category: "bookmark",
    name: "Moon Margin",
    priceCAD: 7,
    image: "assets/bookmark-moon.png",
    descriptions: {
      en: "A moon-and-stars vibe for late-night reading.",
      fr: "Une vibe lune et etoiles pour les lectures du soir.",
    },
  },
  {
    id: "valentina",
    category: "bookmark",
    name: "Valentina",
    priceCAD: 11.5,
    image: "assets/bookmark-rose.png",
    descriptions: {
      en: "A romantic bookmark inspired by Valentina by Kiara Diamant.",
      fr: "Un marque-page romantique inspire de Valentina par Kiara Diamant.",
    },
  },
  {
    id: "blush-shelf",
    category: "kindle",
    name: "Blush Shelf",
    priceCAD: 9.5,
    image: "assets/kindle-blush.png",
    descriptions: {
      en: "An elegant pink insert for a clear Kindle case.",
      fr: "Un insert rose elegant pour coque Kindle transparente.",
    },
  },
  {
    id: "pearl-reader",
    category: "kindle",
    name: "Pearl Reader",
    priceCAD: 9.5,
    image: "assets/kindle-pearl.png",
    descriptions: {
      en: "A pearl and blush design that feels subtle and chic.",
      fr: "Un design nacre et blush, discret mais tres chic.",
    },
  },
  {
    id: "greenhouse",
    category: "kindle",
    name: "Greenhouse",
    priceCAD: 9.5,
    image: "assets/kindle-greenhouse.png",
    descriptions: {
      en: "A fresh green insert with a soft golden detail.",
      fr: "Un insert vert frais avec une touche de jaune doux.",
    },
  },
];

const translations = {
  en: {
    navBookmarks: "Bookmarks",
    navKindle: "Kindle Inserts",
    navDeals: "Deals",
    navFaq: "FAQ",
    languageLabel: "Language",
    currencyLabel: "Currency",
    heroEyebrow: "Bookmarks and Kindle inserts made with love",
    heroText: "Cute, classy reading accessories made to match your current book, your Kindle, and your mood.",
    shopBookmarks: "Shop bookmarks",
    shopKindle: "Shop Kindle inserts",
    trustSmall: "Small business",
    trustCute: "Cute and classy designs",
    trustCustom: "Custom options",
    trustEasy: "Easy ordering",
    bookmarkEyebrow: "Bookmarks",
    bookmarkTitle: "Pretty page holders",
    bookmarkIntro: "Soft, decorative bookmarks for paperbacks, hardcovers, planners, and gifting.",
    kindleEyebrow: "Kindle Inserts",
